import { v4 as uuidv4 } from "uuid";
import { getAdapter } from "../driver.js";
import { parseJson, stringifyJson } from "../helpers/jsonCol.js";
const now = () => new Date().toISOString();
const map = (row) => { if (!row) return null; const out = { ...row }; for (const k of ["config", "result", "metadata", "metrics"]) if (k in out) out[k] = parseJson(out[k], {}); return out; };
export async function getSwarmSessions(filter = {}) { const db = await getAdapter(), args = [], where = []; for (const k of ["status", "strategy"]) if (filter[k] !== undefined) { where.push(`${k}=?`); args.push(filter[k]); } return db.all(`SELECT * FROM swarmSessions ${where.length ? `WHERE ${where.join(" AND ")}` : ""} ORDER BY createdAt DESC`, args).map(map); }
export async function getSwarmSessionById(id) { const db = await getAdapter(); return map(db.get("SELECT * FROM swarmSessions WHERE id=?", [id])); }
export async function createSwarmSession(data) { if (!data?.targetObjective) throw new Error("Swarm targetObjective is required"); const db = await getAdapter(), t = now(), s = { id: data.id || uuidv4(), name: data.name || "Swarm", strategy: data.strategy || "aco", status: data.status || "pending", targetObjective: data.targetObjective, config: data.config || {}, result: null, createdAt: t, updatedAt: t, startedAt: null, completedAt: null }; db.run("INSERT INTO swarmSessions (id,name,strategy,status,targetObjective,config,result,createdAt,updatedAt,startedAt,completedAt) VALUES (?,?,?,?,?,?,?,?,?,?,?)", [s.id,s.name,s.strategy,s.status,s.targetObjective,stringifyJson(s.config),null,t,t,null,null]); return map(s); }
export async function updateSwarmSession(id, updates) { const existing = await getSwarmSessionById(id); if (!existing) return null; const db = await getAdapter(), s = { ...existing, ...updates, updatedAt: now() }; db.run("UPDATE swarmSessions SET name=?,strategy=?,status=?,targetObjective=?,config=?,result=?,updatedAt=?,startedAt=?,completedAt=? WHERE id=?", [s.name,s.strategy,s.status,s.targetObjective,stringifyJson(s.config || {}),s.result == null ? null : stringifyJson(s.result),s.updatedAt,s.startedAt || null,s.completedAt || null,id]); return map(s); }
export async function deleteSwarmSession(id) { const db = await getAdapter(); db.run("DELETE FROM swarmSessions WHERE id=?", [id]); return true; }
export async function addBotToSwarm(swarmId, botId, role = null) { const db = await getAdapter(), row = { id: uuidv4(), swarmId, botId, role, status: "active", joinedAt: now(), leftAt: null, metadata: {} }; db.run("INSERT INTO swarmBots (id,swarmId,botId,role,status,joinedAt,leftAt,metadata) VALUES (?,?,?,?,?,?,?,?) ON CONFLICT(swarmId,botId) DO UPDATE SET role=excluded.role,status='active',leftAt=NULL", [row.id,swarmId,botId,role,"active",row.joinedAt,null,"{}"]); return getSwarmBots(swarmId); }
export async function removeBotFromSwarm(swarmId, botId) { const db = await getAdapter(); db.run("UPDATE swarmBots SET status='removed',leftAt=? WHERE swarmId=? AND botId=?", [now(),swarmId,botId]); return true; }
export async function getSwarmBots(swarmId) { const db = await getAdapter(); return db.all("SELECT * FROM swarmBots WHERE swarmId=? AND status != 'removed' ORDER BY joinedAt ASC", [swarmId]).map(map); }
export async function depositPheromone(swarmId, pathKey, amount, meta = {}) { const db = await getAdapter(), t = now(); db.run("INSERT INTO swarmPheromones (id,swarmId,pathKey,depositAmount,reinforcementValue,strength,metadata,createdAt,updatedAt) VALUES (?,?,?,?,?,?,?,?,?) ON CONFLICT(swarmId,pathKey) DO UPDATE SET depositAmount=depositAmount+excluded.depositAmount,reinforcementValue=reinforcementValue+excluded.reinforcementValue,strength=strength+excluded.strength,metadata=excluded.metadata,updatedAt=excluded.updatedAt", [uuidv4(),swarmId,pathKey,amount,amount,amount,stringifyJson(meta),t,t]); return getPheromones(swarmId); }
export async function decayPheromones(swarmId, decayFactor) { const db = await getAdapter(); db.run("UPDATE swarmPheromones SET strength=MAX(0,strength*(1-?)),updatedAt=? WHERE swarmId=?", [decayFactor,now(),swarmId]); return getPheromones(swarmId); }
export async function getPheromones(swarmId, minStrength = 0) { const db = await getAdapter(); return db.all("SELECT * FROM swarmPheromones WHERE swarmId=? AND strength>=? ORDER BY strength DESC", [swarmId,minStrength]).map(map); }
export async function recordColonyIteration(data) { const db = await getAdapter(), row = { id:data.id || uuidv4(), swarmId:data.swarmId, iteration:data.iteration, phase:data.phase || "exploration", explorationRate:data.explorationRate ?? .5, exploitationRate:data.exploitationRate ?? .5, bestPath:data.bestPath || null, metrics:data.metrics || {}, startedAt:data.startedAt || null, completedAt:data.completedAt || null, createdAt:now() }; db.run("INSERT INTO swarmColonyIterations (id,swarmId,iteration,phase,explorationRate,exploitationRate,bestPath,metrics,startedAt,completedAt,createdAt) VALUES (?,?,?,?,?,?,?,?,?,?,?)", [row.id,row.swarmId,row.iteration,row.phase,row.explorationRate,row.exploitationRate,row.bestPath,stringifyJson(row.metrics),row.startedAt,row.completedAt,row.createdAt]); return map(row); }
export async function getColonyIterations(swarmId) { const db = await getAdapter(); return db.all("SELECT * FROM swarmColonyIterations WHERE swarmId=? ORDER BY iteration ASC", [swarmId]).map(map); }
export async function recordConvergenceMetric(data) { const db = await getAdapter(), row = { id:data.id || uuidv4(), swarmId:data.swarmId, iterationId:data.iterationId || null, iteration:data.iteration, variance:data.variance || 0, consensusScore:data.consensusScore || 0, convergenceScore:data.convergenceScore || 0, converged:data.converged ? 1 : 0, sampleCount:data.sampleCount || 0, metadata:data.metadata || {}, createdAt:now() }; db.run("INSERT INTO swarmConvergenceMetrics (id,swarmId,iterationId,iteration,variance,consensusScore,convergenceScore,converged,sampleCount,metadata,createdAt) VALUES (?,?,?,?,?,?,?,?,?,?,?)", [row.id,row.swarmId,row.iterationId,row.iteration,row.variance,row.consensusScore,row.convergenceScore,row.converged,row.sampleCount,stringifyJson(row.metadata),row.createdAt]); return map(row); }
export async function getConvergenceHistory(swarmId) { const db = await getAdapter(); return db.all("SELECT * FROM swarmConvergenceMetrics WHERE swarmId=? ORDER BY iteration ASC", [swarmId]).map(map); }
